### ISSUE TITLE
juce7

### ISSUE THREAD

**Issue by benediktadams** [parawave/vulkan-cpp-library#2]
Hi, 
has this been tested with juce7 yet? 

I just tried implementing it and while adding the module/sdk was simple enough, this is all I can get... 

![Screenshot 2022-07-21 180954](https://user-images.githubusercontent.com/20302171/180284127-683911f9-a4dc-4ffc-ace8-6c4b1ab5fa95.png)

When I add a  juce::Timer framerate to the component the context is attached to and call repaint () continuously, it renders correctly, although laggy and with occasional glitches, that look like the above image.  

Any tips?

**Comment by parawave** [comment]
Hi, 

sorry to disappoint. The modules aren't really developed anymore. There wasn't much feedback from the JUCE community, so it never left the initial experimental state. It could be that it also didn't work with JUCE 6. There is no specific dependency on JUCE code that could break it. 

My guess is that the swapchain surface image format isn't compatible. Or the framebuffer vs swapchain format doesn't match. 
There are many formats available in Vulkan and there isn't much code (yet) that verifies the supported configuration of the driver (or vkInstance).
